[build]
  publish = "build/web"
  command = """
    curl -L https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.0-stable.tar.xz | tar -xJ &&
    export PATH="$PATH:/opt/buildhome/repo/flutter/bin" &&
    flutter config --no-analytics &&
    flutter pub get &&
    flutter build web --release
  """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200